#!/usr/bin/env bash

cd "$(dirname "$0")"

rm -rf "$HOME/.cache/wal/*"

theme='colors.json'
./wal.sh "$theme" -f "$theme"

background="$HOME/.dotfiles/assets/background"
python "$background/generate.py"
feh --bg-center "$background/background.jpg"

